from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from common import KNOWLEDGE_DIR, ROOT, KnowledgeItem, load_items

GENERATED = KNOWLEDGE_DIR / "generated"
BY_TOPIC = GENERATED / "by-topic"
MARKER = "<!-- generated by tools/knowledge/build.py; do not edit -->"


def item_id(item: KnowledgeItem) -> str:
    return str(item.meta.get("id", ""))


def item_link(item: KnowledgeItem, prefix: str = "../items") -> str:
    return f"[{item_id(item)} {item.meta.get('title', '')}]({prefix}/{item.path.name})"


def write_index(path: Path, title: str, items: Iterable[KnowledgeItem]) -> None:
    rows = sorted(items, key=item_id)
    lines = [MARKER, "", f"# {title}", ""]
    if not rows:
        lines.append("_No entries._")
    else:
        for item in rows:
            summary = str(item.meta.get("summary", "")).strip()
            lines.append(f"- {item_link(item)} — {summary}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def slugify(value: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9._-]+", "-", value).strip("-").lower()
    return slug or "topic"


def build_topic_views(items: list[KnowledgeItem]) -> None:
    BY_TOPIC.mkdir(parents=True, exist_ok=True)
    for old in BY_TOPIC.glob("*.md"):
        old.unlink()

    topics: dict[str, list[KnowledgeItem]] = {}
    for item in items:
        for topic in item.meta.get("topics") or []:
            topics.setdefault(str(topic), []).append(item)

    for topic, topic_items in sorted(topics.items()):
        path = BY_TOPIC / f"{slugify(topic)}.md"
        rows = sorted(topic_items, key=item_id)
        lines = [MARKER, "", f"# Topic: {topic}", ""]
        for item in rows:
            summary = str(item.meta.get("summary", "")).strip()
            lines.append(f"- {item_link(item, '../../items')} — {summary}")
        lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")


def build_graph(items: list[KnowledgeItem]) -> None:
    lines = ["%% generated by tools/knowledge/build.py; do not edit", "graph LR"]
    for item in sorted(items, key=item_id):
        iid = item_id(item)
        title = str(item.meta.get("title", "")).replace('"', "'")
        lines.append(f'    {iid}["{iid} {title}"]')

    for item in sorted(items, key=item_id):
        source = item_id(item)
        relations = item.meta.get("relations") or {}
        if not isinstance(relations, dict):
            continue
        for relation, targets in sorted(relations.items()):
            if not isinstance(targets, list):
                continue
            for target in targets:
                lines.append(f"    {source} -->|{relation}| {target}")

    lines.append("")
    (GENERATED / "dependency-graph.mmd").write_text("\n".join(lines), encoding="utf-8")


def build_artifact_index(items: list[KnowledgeItem]) -> None:
    lines = [MARKER, "", "# Artifact index", ""]
    count = 0
    for item in sorted(items, key=item_id):
        artifacts = item.meta.get("artifacts") or []
        if not isinstance(artifacts, list):
            continue
        for artifact in artifacts:
            if not isinstance(artifact, dict):
                continue
            path = artifact.get("path")
            role = artifact.get("role", "")
            if not path:
                continue
            count += 1
            lines.append(f"- `{path}` ({role}) — {item_link(item)}")
    if count == 0:
        lines.append("_No entries._")
    lines.append("")
    (GENERATED / "artifact-index.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    items = load_items()
    GENERATED.mkdir(parents=True, exist_ok=True)

    write_index(
        GENERATED / "open-problems.md",
        "Open problems",
        (
            item
            for item in items
            if item.meta.get("kind") == "open-problem" and item.meta.get("status") == "open"
        ),
    )
    write_index(
        GENERATED / "proved-results.md",
        "Proved results",
        (item for item in items if item.meta.get("status") == "proved"),
    )
    write_index(
        GENERATED / "refuted-items.md",
        "Refuted or invalidated items",
        (
            item
            for item in items
            if item.meta.get("status") in {"refuted", "invalidated", "withdrawn"}
        ),
    )
    build_topic_views(items)
    build_graph(items)
    build_artifact_index(items)

    print(f"knowledge build: generated views from {len(items)} items")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
