#!/usr/bin/env python3
"""Exhaustive audit of pre-known exact LOSS children in git history prior to preregistration,
and sensitivity analysis recomputing holdout ranking performance after excluding all such pre-known witnesses.
"""

from __future__ import annotations

import csv
import json
import math
import re
import statistics
import subprocess
from io import StringIO
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
BASE_SHA = "46b4e50"

OUT_CSV = REPO_ROOT / "results" / "10x10" / "exhaustive_preknown_loss_audit.csv"
OUT_JSON = REPO_ROOT / "results" / "10x10" / "exhaustive_preknown_loss_audit.json"
OUT_DETAILS_CSV = REPO_ROOT / "results" / "10x10" / "exhaustive_preknown_loss_details.csv"

import sys
sys.path.insert(0, str(REPO_ROOT / "scripts"))
from analyze_probe_holdout_preregistered import (
    CHILDREN_DIR,
    OUT_DIR,
    SELECTION,
    auc_from_order,
    corrected_key,
    first_loss_rank,
    load_children,
    load_exact,
    load_parents,
    load_probe,
    norm_state,
    one_sided_sign_p,
    random_median,
)


def ints(s: str) -> tuple[int, ...]:
    return tuple(sorted(int(x) for x in s.replace("-", ",").split(",") if x.strip()))


def d4_point(p: int, k: int, n: int = 10) -> int:
    x, y = p % n, p // n
    xy = [
        (x, y), (n - 1 - x, y), (x, n - 1 - y), (n - 1 - x, n - 1 - y),
        (y, x), (n - 1 - y, x), (y, n - 1 - x), (n - 1 - y, n - 1 - x),
    ][k]
    return xy[1] * n + xy[0]


def d4_states(state: str) -> set[str]:
    xs = ints(state)
    return {norm_state("-".join(str(d4_point(p, k)) for p in xs)) for k in range(8)}


def canonical(state: str) -> str:
    return min(d4_states(state))


def get_commit_info(path: str, base_sha: str) -> str:
    res = subprocess.run(
        ["git", "log", "-n", "1", "--format=%h %as %s", base_sha, "--", path],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    return res.stdout.strip()


def find_preknown_losses(base_sha: str, child_lookup: dict[str, list[tuple[str, str, str]]]):
    """Scan all files at base_sha for exact 4-stone LOSS occurrences."""
    res = subprocess.run(
        ["git", "ls-tree", "-r", "--name-only", base_sha],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=True,
    )
    all_files = [f for f in res.stdout.splitlines() if f.endswith((".csv", ".txt", ".json", ".md"))]

    records = []
    seen_file_states = set()

    for fpath in all_files:
        if "blind_probe_children" in fpath and "probe_" in fpath:
            continue
        # Skip output files generated by later runs if somehow present
        if "blind-probe-holdout" in fpath and "exact_outcomes" in fpath:
            continue

        p = subprocess.run(
            ["git", "show", f"{base_sha}:{fpath}"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        if p.returncode != 0:
            continue
        content = p.stdout

        if fpath.endswith(".csv"):
            reader = csv.reader(StringIO(content))
            header = next(reader, None)
            if not header:
                continue
            header_lower = [h.lower() for h in header]

            for row_idx, row in enumerate(reader):
                for col_idx, val in enumerate(row):
                    val = val.strip()
                    if val.count(",") == 3 or val.count("-") == 3:
                        try:
                            pts = ints(val)
                            if len(pts) == 4 and all(0 <= x < 100 for x in pts):
                                s_canon = canonical("-".join(str(x) for x in pts))
                                if s_canon in child_lookup:
                                    is_loss = False
                                    col_name = header_lower[col_idx] if col_idx < len(header_lower) else ""
                                    if col_name == "loss_child":
                                        is_loss = True
                                    elif "outcome" in header_lower:
                                        out_col = header_lower.index("outcome")
                                        if out_col < len(row) and row[out_col].strip().upper() == "LOSS":
                                            is_loss = True
                                    elif "four-stone-loss-proof" in fpath or "five-stone-loss-proof" in fpath:
                                        if "outcome" in header_lower:
                                            out_col = header_lower.index("outcome")
                                            if out_col < len(row) and row[out_col].strip().upper() == "LOSS":
                                                is_loss = True
                                        else:
                                            is_loss = True
                                    elif "loss" in fpath.lower() and "subsets" in fpath.lower():
                                        is_loss = True

                                    if is_loss:
                                        key = (fpath, val, s_canon)
                                        if key not in seen_file_states:
                                            seen_file_states.add(key)
                                            for parent, lit_child, exact_val in child_lookup[s_canon]:
                                                records.append({
                                                    "file": fpath,
                                                    "row_idx": row_idx,
                                                    "col_name": col_name,
                                                    "val": val,
                                                    "canon": s_canon,
                                                    "parent": parent,
                                                    "literal_child": lit_child,
                                                    "exact_outcome": exact_val,
                                                })
                        except Exception:
                            pass
        elif fpath.endswith(".json"):
            # Check JSON files for loss patterns
            pat = re.findall(r"[\"'](\d{1,2}[,\-]\d{1,2}[,\-]\d{1,2}[,\-]\d{1,2})[\"']", content)
            for val in pat:
                try:
                    pts = ints(val)
                    if len(pts) == 4 and all(0 <= x < 100 for x in pts):
                        s_canon = canonical("-".join(str(x) for x in pts))
                        if s_canon in child_lookup:
                            # Verify if mentioned as loss in context
                            # Look at surrounding 200 chars
                            pos = content.find(val)
                            context = content[max(0, pos - 100):min(len(content), pos + 100)].lower()
                            if "loss" in context:
                                key = (fpath, val, s_canon)
                                if key not in seen_file_states:
                                    seen_file_states.add(key)
                                    for parent, lit_child, exact_val in child_lookup[s_canon]:
                                        records.append({
                                            "file": fpath,
                                            "row_idx": -1,
                                            "col_name": "json_context",
                                            "val": val,
                                            "canon": s_canon,
                                            "parent": parent,
                                            "literal_child": lit_child,
                                            "exact_outcome": exact_val,
                                        })
                except Exception:
                    pass

    return records


def main():
    parents = load_parents()
    probes = load_probe()

    child_lookup = {}
    for p in parents:
        ch = load_children(p)
        ex = load_exact(p)
        for c in ch:
            c_canon = canonical(c)
            if c_canon not in child_lookup:
                child_lookup[c_canon] = []
            child_lookup[c_canon].append((p, c, ex[c]))

    print(f"Auditing preknown LOSS children for {len(parents)} parents against git tree at {BASE_SHA}...")
    records = find_preknown_losses(BASE_SHA, child_lookup)
    print(f"Total matching preknown loss occurrences found: {len(records)}")

    # Group by parent and child
    by_parent_child = {}
    commit_cache = {}

    for r in records:
        p = r["parent"]
        c = r["literal_child"]
        if (p, c) not in by_parent_child:
            by_parent_child[(p, c)] = []
        fpath = r["file"]
        if fpath not in commit_cache:
            commit_cache[fpath] = get_commit_info(fpath, BASE_SHA)
        r["commit_info"] = commit_cache[fpath]
        by_parent_child[(p, c)].append(r)

    # Compile detail rows for each preknown child
    detail_rows = []
    preknown_children_by_parent = {p: set() for p in parents}

    for (p, c), recs in by_parent_child.items():
        preknown_children_by_parent[p].add(c)
        ch_list = load_children(p)
        ex_map = load_exact(p)
        pmap = {(p, s): probes[(p, s)] for s in ch_list}
        order = sorted(ch_list, key=lambda s: corrected_key(p, s, pmap[(p, s)]))
        memo_rank = order.index(c) + 1
        memo_val = int(probes[(p, c)]["memo"])
        primary_file = recs[0]["file"]
        primary_commit = recs[0]["commit_info"]
        all_files = "; ".join(sorted(set(r["file"] for r in recs)))

        detail_rows.append({
            "parent": p,
            "literal_child": c,
            "canonical_child": canonical(c),
            "exact_outcome": ex_map[c],
            "memo_rank": memo_rank,
            "memo": memo_val,
            "source_file": primary_file,
            "source_commit": primary_commit,
            "all_sources": all_files,
            "occurrences": len(recs),
        })

    detail_rows.sort(key=lambda r: (r["parent"], r["memo_rank"]))

    with OUT_DETAILS_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(detail_rows[0].keys()))
        writer.writeheader()
        writer.writerows(detail_rows)
    print(f"Wrote {len(detail_rows)} preknown LOSS detail rows to {OUT_DETAILS_CSV}")

    # Re-run sensitivity analysis per parent excluding ALL pre-known LOSS children
    parent_summary_rows = []
    before_aucs = []
    after_aucs = []

    for p in parents:
        children = load_children(p)
        exact = load_exact(p)
        m = len(children)
        l = sum(1 for s in children if exact[s] == "LOSS")
        preknown_set = preknown_children_by_parent[p]
        k = len(preknown_set)

        pmap = {(p, s): probes[(p, s)] for s in children}
        order_before = sorted(children, key=lambda s: corrected_key(p, s, pmap[(p, s)]))
        rank_before = first_loss_rank(order_before, exact)
        med_before = random_median(m, l)
        auc_before = auc_from_order(order_before, exact)
        if auc_before is not None:
            before_aucs.append(auc_before)

        # Exclude preknown LOSS children
        kept = [s for s in children if s not in preknown_set]
        kept_exact = {s: exact[s] for s in kept}
        remaining_loss = sum(1 for s in kept if kept_exact[s] == "LOSS")
        m_after = len(kept)

        if remaining_loss > 0:
            order_after = [s for s in order_before if s not in preknown_set]
            rank_after = first_loss_rank(order_after, kept_exact)
            med_after = random_median(m_after, remaining_loss)
            relation = "better" if rank_after < med_after else "worse" if rank_after > med_after else "tie"
            auc_after = auc_from_order(order_after, kept_exact)
            if auc_after is not None:
                after_aucs.append(auc_after)
        else:
            rank_after = None
            med_after = None
            relation = "no_remaining_loss"
            auc_after = None

        preknown_ranks = sorted([order_before.index(c) + 1 for c in preknown_set])
        was_rank1_preknown = 1 in preknown_ranks

        parent_summary_rows.append({
            "parent": p,
            "m_candidates": m,
            "l_exact_loss": l,
            "k_preknown_loss": k,
            "preknown_memo_ranks": str(preknown_ranks),
            "was_rank1_preknown": was_rank1_preknown,
            "first_loss_rank_before": rank_before,
            "random_median_before": med_before,
            "auc_before": auc_before,
            "m_remaining": m_after,
            "l_remaining_loss": remaining_loss,
            "first_loss_rank_after": rank_after,
            "random_median_after": med_after,
            "relation_after": relation,
            "auc_after": auc_after,
        })

    eligible = [r for r in parent_summary_rows if r["relation_after"] != "no_remaining_loss"]
    better = sum(1 for r in eligible if r["relation_after"] == "better")
    tie = sum(1 for r in eligible if r["relation_after"] == "tie")
    worse = sum(1 for r in eligible if r["relation_after"] == "worse")
    sign_p = one_sided_sign_p(better, worse)

    summary = {
        "analysis": "exhaustive preknown LOSS witness exclusion sensitivity analysis",
        "base_sha": BASE_SHA,
        "total_parents": len(parent_summary_rows),
        "parents_with_remaining_loss": len(eligible),
        "parents_where_rank1_was_preknown": sum(1 for r in parent_summary_rows if r["was_rank1_preknown"]),
        "better_after": better,
        "tie_after": tie,
        "worse_after": worse,
        "sign_p_after": sign_p,
        "mean_auc_before": statistics.mean(before_aucs),
        "median_auc_before": statistics.median(before_aucs),
        "mean_auc_after": statistics.mean(after_aucs) if after_aucs else None,
        "median_auc_after": statistics.median(after_aucs) if after_aucs else None,
    }

    with OUT_CSV.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(parent_summary_rows[0].keys()))
        writer.writeheader()
        writer.writerows(parent_summary_rows)

    with OUT_JSON.open("w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("\n--- Exhaustive Preknown Loss Audit Summary ---")
    print(json.dumps(summary, indent=2))
    print("\nParent by parent results:")
    print(f"{'Parent':<10} {'m':<4} {'l':<4} {'k':<4} {'Preknown Ranks':<25} {'R1_Pre':<7} {'RankBef':<8} {'RankAft':<8} {'MedAft':<7} {'Rel':<7} {'AUC_Bef':<8} {'AUC_Aft':<8}")
    for r in parent_summary_rows:
        auc_b_str = f"{r['auc_before']:.3f}" if r['auc_before'] is not None else "N/A"
        auc_a_str = f"{r['auc_after']:.3f}" if r['auc_after'] is not None else "N/A"
        rank_a_str = str(r['first_loss_rank_after']) if r['first_loss_rank_after'] is not None else "None"
        med_a_str = str(r['random_median_after']) if r['random_median_after'] is not None else "None"
        print(f"{r['parent']:<10} {r['m_candidates']:<4} {r['l_exact_loss']:<4} {r['k_preknown_loss']:<4} {r['preknown_memo_ranks']:<25} {str(r['was_rank1_preknown']):<7} {r['first_loss_rank_before']:<8} {rank_a_str:<8} {med_a_str:<7} {r['relation_after']:<7} {auc_b_str:<8} {auc_a_str:<8}")


if __name__ == "__main__":
    main()
